services:
  minio:
    image: minio/minio
    container_name: datalake-minio
    hostname: minio
    ports:
      - "9000:9000"   # Port cho API
      - "9090:9090"   # Port cho giao diện điều khiển
    volumes:
      - minio_storage:/mnt/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9090" /mnt/data

volumes:
  minio_storage:  # Định nghĩa volume