nyc_data:
    folder_path: /data
    taxi_lookup_file: /data/taxi_lookup.parquet
datalake:
    endpoint: localhost:9000
    bucket_name_1: raw
    bucket_name_2: processed
    bucket_name_3: sandbox
    folder_name: batch
    access_key: Xs27nx9M4HgPQ5PXZiUE
    secret_key: 8iifKZlUZh1NRbepsISUMdg1CxlaIC6OSPQk5X59
